api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    exception_to_status:
        \Exception: 200
        Symfony\Component\Serializer\Exception\ExceptionInterface: 200 # Use a raw status code (recommended)
        ApiPlatform\Exception\InvalidArgumentException: 200
        ApiPlatform\Exception\FilterValidationException: 200